/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 12.2.0-14+deb12u1 -fPIC -O3) */

module WiredNet(data1, data2, out_wired);
  input data1;
  wire data1;
  input data2;
  wire data2;
  output out_wired;
  wire out_wired;
  wire w_or;
  assign data2 = data1;
  assign out_wired = data1;
  assign w_or = data1;
endmodule
