/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 12.2.0-14+deb12u1 -fPIC -O3) */

module topi(clk, out2);
  wire _0_;
  input clk;
  wire clk;
  output out2;
  reg out2;
  reg q1;
  always_ff @(posedge clk)
    out2 <= _0_;
  always_ff @(posedge clk)
    q1 <= 1'h0;
  assign _0_ = q1 ? 1'h1 : out2;
endmodule
